---
output: 
  html_document: 
    keep_md: yes
    self_contained: no
---
***
#### PROFESSIONAL EXPERIENCE

[**PROCTER & GAMBLE INC.**](http://www.pg.ca)    
**Retail Data Analytics Specialist Walmart Canada Team**  
Toronto, Canada  
Nov 2014 – Dec 2015  

* Disrupted Canada POS data ETL process, reducing SLA from 20 to 3 days, enabling Customer Teams sell with bigger, better and faster data insights. At Walmart Canada only, it resulted in winning Category Captaincy in Oral Care, Fem Care and Baby Care representing a ~$5million annual POS increase
* Designed a Brands Feature co-dependence regression analysis to maximize Feature ROI and Market Share growth
* Recognized as an internal KNIME Subject-Matter-Expert. Led a P&G Global KNIME Trainings from the Toronto GO
* Recognized as an R advanced user, created dashboards and supported to other Canadian Analysts writing scripts
* Shared & Reapplied Spotfire templates to analyze the impact on the business of Private Label at Walmart Canada
* Pitched to Senior Mgmt. leveraging P&G’s HDFS to further improve POS data ETL process using Sqoop and Hive

[**PROCTER & GAMBLE INC.**](http://www.pg.ca)  
**Retail Replenishment Analyst, Walmart Canada Team**
Toronto, Canada  
Jul 2013 – Oct 2014  

* P&G’s Health & Beauty supply chain replenishment owner, supporting a business generating $250million annually
* Generated $5.8 million in incremental supply chain driven sales through analytics and replenishment interventions
* Grew Femme Care POS by 4% ($2million) and Shaving POS by 4% ($1million) over a 4 months period by pioneering a “How high is up” inventory and forecast pilot project across Walmart Canada Stores
* Delivered time savings of 120 man hours per month by redesigning and automating forecast and replenishment processes that impact across P&G’s entire portfolio at Walmart
* Increased P&G’s product portfolio in-stock (+1% VYA) by revamping replenishment weekly in-stock reporting allowing eleven team members to readily ID opportunities, root causes and drive to resolution faster 
* Streamlined 24/7 customer service coverage for the largest P&G scale event in North America delivering 100 hours staffing requirement decrease and 100% reported data integrity (+10% VYA). 

[**PROCTER & GAMBLE INC.**](http://www.pg.ca)  
**On Shelf Availability Analyst, Walmart Canada Team**  
Toronto, Canada  
Mar 2013 – Jun 2013  

* Identified potential phantom inventory instances at Walmart Stores by developing a dashboard based on POS data

[**FUTURE ELECTRONICS**](www.futureelectronics.com/)  
**Supply Chain Consultant**  
Montreal, Canada  
Jun 2012 – Nov 2012  

* Achieved 10% savings in internal transportation costs ($120,000) by replacing shipping method on strategic SKUs

	
[**BOMBARDIER AEROSPACE**](http://www.bombardier.com/en/aerospace.html)  
**Supply Chain System Dynamics Analyst (Independent Study)**  
Montreal, Canada  
May 2011 – Sep 2011  

* Developed system dynamics model to analyze aerospace fasteners’ supply chain behavior 
* Identified key factors disturbing the system model and simulated alternative policies to improve overall performance
* Evaluated potential outcomes of Vendor Management Inventory and Third Party Logistics strategies
* Appraised final results of analysis to senior management. Conducted weekly client update sessions
* Co-wrote paper presented and published at the 30th International Conference of the System Dynamics Society: [Industry Analysis: The Fastener Supply Chain in Aerospace Industry](http://www.systemdynamics.org/conferences/2012/proceed/papers/P1296.pdf)

**FENWICK AUTOMOTIVE PARTS**  
**Maintenance Repair and Operations Buyer**  
Monterrey, Mexico  
Mar 2010 – Aug 2010  

* Achieved 30% cost savings by replacing packaging suppliers identified through cardboard benchmark
* Developed Excel spreadsheet model to evaluate corporate proposal for a NAFTA supply consortium

[**INTEGRATION ENGINEERING AND CONSTRUCTION SYSTEMS**](http://www.iecos.com/)  
**Supply Services Manager**  
Monterrey, Mexico  
Aug 2006 – Mar 2010  

* Increased 300% monthly revenues ($10,000) by planning, forecasting and implementing a replenishment program
* Reduced Purchasing Orders’ processing time by 50% via standardization and documentation controls
* Managed Small and Medium Businesses by integrating production capabilities in manufacturing clusters 

***
#### EDUCATION
**McGILL UNIVERSITY** 	
**Master in Manufacturing Management, Supply Chain and Global Operations**  
Montreal, Canada  
Aug 2010 – Nov 2012

**TECNOLÓGICO DE MONTERREY (ITESM)**  
**Bachelor of Science in Mechanical Engineering, Minor in Industrial Engineering**  
Monterrey, Mexico  
Aug 2000 – Dec 2006  

***
#### HONORS AND AWARDS


* **McGill MMM program performance scholarship**, awarded to top qualified students during the Fall 2010 semester
* **P&G’s “Execute with Excellence” Pearl Award** for groundbreaking results in “How High is Up” Fem Care pilot project 

***
#### CERTIFICATIONS AND SKILLS

**Certifications:**  

* Six Sigma Green Belt (2011)
* Lean Project Leader (2011)
* [Coursera's Data Scientist Specialization](https://www.coursera.org/account/accomplishments/specialization/VW3QXBQ4HR8J) (2015)

**Languages:**

* Spanish (native)
* English (fluent) 

**Software:**  

* Access, AutoCAD, iGrafx, MS Office (Excel, Word, PowerPoint, Outlook), Solver (linear programming), Oracle Crystal Ball (predictive modeling, GitHub, Monte Carlo simulations & forecasting), KNIME, ADConnect (Nielsen), Prezi, Pro-Engineer, ProModel, Vensim, Visio, Visual Basic (VBA), Retail Link, R, RStudio, Shiny Apps, TIBCO Spotfire, some (C++, JavaScript, Python and SQL)

**Extracurricular:** 

* Canvassing System Leader supporting “My Giving Moment” 2014 kickoff event helping reach $265,000 goal by developing and maintaining an interactive multi-channel live pledging platform (Toronto, Canada)
* Co-authored Case Study about Saputo Inc. for the Export Development Canada (EDC) (Montreal, Canada)

